name: etanois
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  dartz: ^0.9.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.1.2
  mobx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

scripts:
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs