name: etanois
description: Aplicação mobile para o Etanóis, um motor de busca por postos de combustível pela localização do usuário

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.1
  flutter:
    sdk: flutter

  dio: ^3.0.9
  flutter_mobx: ^1.1.0
  flutter_modular: ^1.2.5+1
  mobx: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  mockito: ^4.1.1

flutter:
  uses-material-design: true

scripts:
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs
