name: etanois
description: Aplicação mobile para o Etanóis, um motor de busca por postos de combustível a partir da localização do usuário e de suas preferências.

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dartz: ^0.9.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  flutter_modular: ^1.3.1
  get_it: ^4.0.4
  intl: ^0.16.1
  mobx: ^1.2.1+1

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0+1
  mockito: ^4.1.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/menu.png
    - assets/icons/moon.png
    - assets/icons/radar.png
    - assets/icons/route.png
    - assets/icons/send_message.png

    - assets/map.style.txt

vars:
  # MOBX
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

  # ADB
  ip: '192.168.20.106'
  port: '5555'

scripts:
  # MOBX
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs

  # ADB
  adb_connect: adb connect $ip:$port
  adb_disconnect: adb disconnect $ip:$port
